src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\InheritanceType('SINGLE_TABLE')]
#[ORM\DiscriminatorColumn(name: 'user_type', type: 'string')]
#[ORM\DiscriminatorMap([
    'user' => User::class,
    'admin' => Admin::class,
    'student' => Student::class,
    'teacher' => Teacher::class
])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $pseudo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Participation::class, cascade: ['persist', 'remove'])]
    private Collection $participations;

    /**
     * @var Collection<int, DebateMessage>
     */
    #[ORM\OneToMany(targetEntity: DebateMessage::class, mappedBy: 'author')]
    private Collection $debateMessages;

    public function __construct()
    {
        $this->participations = new ArrayCollection();
        $this->debateMessages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getParticipations(): Collection
    {
        return $this->participations;
    }

    public function addParticipation(Participation $participation): static
    {
        if (!$this->participations->contains($participation)) {
            $this->participations->add($participation);
            $participation->setUser($this);
        }
        return $this;
    }

    public function removeParticipation(Participation $participation): static
    {
        if ($this->participations->removeElement($participation)) {
            if ($participation->getUser() === $this) {
                $participation->setUser(null);
            }
        }
        return $this;
    }

    public function getRoles(): array
    {
        return match (true) {
            $this instanceof Student => ['ROLE_USER', 'ROLE_STUDENT'],
            $this instanceof Teacher => ['ROLE_USER', 'ROLE_TEACHER'],
            $this instanceof Admin => ['ROLE_USER', 'ROLE_ADMIN'],
            default => ['ROLE_USER'],
        };
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function eraseCredentials(): void
    {

    }


    public function getUserType(): string
    {
        return match (true) {
            $this instanceof Student => 'student',
            $this instanceof Teacher => 'teacher',
            $this instanceof Admin => 'admin',
            default => 'user',
        };
    }

    /**
     * @return Collection<int, DebateMessage>
     */
    public function getDebateMessages(): Collection
    {
        return $this->debateMessages;
    }

    public function addDebateMessage(DebateMessage $debateMessage): static
    {
        if (!$this->debateMessages->contains($debateMessage)) {
            $this->debateMessages->add($debateMessage);
            $debateMessage->setAuthor($this);
        }

        return $this;
    }

    public function removeDebateMessage(DebateMessage $debateMessage): static
    {
        if ($this->debateMessages->removeElement($debateMessage)) {
            // set the owning side to null (unless already changed)
            if ($debateMessage->getAuthor() === $this) {
                $debateMessage->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/DebateController.php
<?php

namespace App\Controller;

use App\Entity\DebateMessage;
use App\Form\DebateMessageType;
use App\Repository\DebateMessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DebateController extends AbstractController
{
    #[Route('/debat', name: 'app_debate')]
    public function index(Request $request, EntityManagerInterface $em, DebateMessageRepository $repo): Response
    {
        $message = new DebateMessage();
        
       
        $replyToId = $request->query->get('replyTo');
        if ($replyToId) {
            $parent = $repo->find($replyToId);
            if ($parent) {
                $message->setParent($parent);
            }
        }
    
        $form = $this->createForm(DebateMessageType::class, $message);
    
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $message->setAuthor($this->getUser());
            $message->setCreatedAt(new \DateTimeImmutable());
            $message->setLikes(0);
            $em->persist($message);
            $em->flush();
    
            return $this->redirectToRoute('app_debate');
        }
    
        $messages = $repo->findBy(['parent' => null], ['createdAt' => 'DESC']);
    
        return $this->render('debate/index.html.twig', [
            'form' => $form->createView(),
            'messages' => $messages
        ]);
    }
    

    #[Route('/debat/like/{id}', name: 'app_debate_like')]
public function like(DebateMessage $message, EntityManagerInterface $em): Response
{
    $message->like();
    $em->flush();

    return $this->redirectToRoute('app_debate');
}

}

templates/debate/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace Débat{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/pages/debate.css') }}">
{% endblock %}

{% block body %}
<h1>
    <img src="{{ asset('images/bulle.jpeg') }}" alt="Bulle de discussion" class="bubble-icon">
    Espace Débat
</h1>



{# -- Formulaire de publication -- #}

{% if app.user %}
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">Envoyer</button>
    {{ form_end(form) }}
{% else %}
  <p class="login-alert">
    <img src="{{ asset('images/cadenas.jpeg') }}" alt="Cadenas" class="lock-icon">
    Tu dois <a href="{{ path('app_login') }}" class="login-link">te connecter</a> pour participer à la discussion.
</p>

{% endif %}

<hr>



{% for msg in messages %}
    <div class="message">
       <p class="author">
    {{ msg.author.email }}
    <span class="role-badge 
        {% if 'ROLE_ADMIN' in msg.author.roles %}
            admin
        {% elseif 'ROLE_TEACHER' in msg.author.roles %}
            teacher
        {% elseif 'ROLE_STUDENT' in msg.author.roles %}
            student
        {% else %}
            user
        {% endif %}
    ">
        {% if 'ROLE_ADMIN' in msg.author.roles %}
            Administrateur
        {% elseif 'ROLE_TEACHER' in msg.author.roles %}
            Enseignant
        {% elseif 'ROLE_STUDENT' in msg.author.roles %}
            Étudiant
        {% else %}
            Utilisateur
        {% endif %}
    </span>
</p>



        <p>{{ msg.content }}</p>

        <p class="meta">
            {{ msg.createdAt|date('d/m/Y H:i') }}
            <a href="{{ path('app_debate_like', { id: msg.id }) }}" style="text-decoration: none; margin-left: 10px;">❤️ {{ msg.likes }}</a>
            {% if app.user %}
                <a href="{{ path('app_debate', { replyTo: msg.id }) }}" style="text-decoration: none; margin-left: 10px;">💬 Répondre</a>
            {% endif %}
        </p>


        {% for reply in msg.replies %}
    <div class="message" style="margin-left: 30px; background: #f8f8f8;">
       <p class="author">
    {{ msg.author.email }}
    <span class="role-badge 
        {% if 'ROLE_ADMIN' in msg.author.roles %}
            admin
        {% elseif 'ROLE_TEACHER' in msg.author.roles %}
            teacher
        {% elseif 'ROLE_STUDENT' in msg.author.roles %}
            student
        {% else %}
            user
        {% endif %}
    ">
        {% if 'ROLE_ADMIN' in msg.author.roles %}
            Administrateur
        {% elseif 'ROLE_TEACHER' in msg.author.roles %}
            Enseignant
        {% elseif 'ROLE_STUDENT' in msg.author.roles %}
            Étudiant
        {% else %}
            Utilisateur
        {% endif %}
    </span>
</p>

        <p>{{ reply.content }}</p>
        <p class="meta">
            {{ reply.createdAt|date('d/m/Y H:i') }}
            <a href="{{ path('app_debate_like', { id: reply.id }) }}" style="text-decoration: none; margin-left: 10px;">❤️ {{ reply.likes }}</a>
        </p>
    </div>
{% endfor %}

    </div>
{% else %}
    <p>Aucun message pour le moment.</p>
{% endfor %}
{% endblock %}